version: "3.8"
services:
  db-yii2:
    image: mysql:5.7.31
    container_name: yii2.db
    hostname: db.yii2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PWD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${DB_ALLOW_EMPTY_PWD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - 3307:3306
    volumes:
      - yii2_data:/var/lib/mysql
    networks:
      - yii2-network

  yii2-basic: # http://localhost:3306
    build:
      context: .
    image: yii2/basic
    container_name: yii2.basic
    hostname: basic.yii2
    ports:
      - 3306:80
    volumes:
      - ./app:/var/www/html/

    working_dir: /var/www/html/
    networks:
      - yii2-network
    command: php -S 0.0.0.0:80 -t web/

networks:
  yii2-network:
    driver: bridge

volumes:
  yii2_data: